### ISSUE TITLE
Partial not included - No partial found in any _private directory

### ISSUE THREAD

**Issue by bartonhammond** [benallfree/pocketpages#15]
Partial is `app/pages/_todo-list.ejs`

I've tried numerous combinations for the path but get same error regardless.  

main template: `app/pages/index.ejs`
```
	<%- include(`./_todo-list.ejs`, data) %>
```
Error:

```
Error: /index.ejs:16
    14|     
    15|     Mark all as complete
 >> 16| 	<%- include(`_todo-list.ejs`, data) %>
    17|   
    18|   
    19|   


No partial '_todo-list.ejs' found in any _private directory
	at node_modules/pocketpages/src/lib/ejs.ts:57:8(78)
	at getIncludePath (node_modules/pocketpages/node_modules/pocketbase-ejs/lib/ejs.js:174:40(53))
	at includeFile (node_modules/pocketpages/node_modules/pocketbase-ejs/lib/ejs.js:310:33(14))
	at include (node_modules/pocketpages/node_modules/pocketbase-ejs/lib/ejs.js:700:27(22))
	at anonymous (:12:24(32))
```

**Comment by benallfree** [comment]
Something went wrong with the npm release and it's installing v0.10-rc for people instead of v0.9. You might try downgrading to 0.9 because it matches the online docs.

Put partials in a `_private` folder if using v0.10, subject to change :)

**Comment by bartonhammond** [comment]
updated `package.json` to `    "pocketpages": "^0.9",` and it now works
