### ISSUE TITLE
How to return HTML to support HTMX

### ISSUE THREAD

**Issue by bartonhammond** [benallfree/pocketpages#16]
On my form to create a todo, I have:
```
<form hx-post="/newtodo" hx-trigger="submit" hx-target=".todo-list" hx-swap="afterbegin" hx-on::after-request="this.reset()" hx-swap="none">
      <input name="todo" class="new-todo" placeholder="What needs to be done?" autofocus>
    </form>
```
This calls into route properly:
```
routerAdd("POST", "/newtodo", (c) => {
	const data = $apis.requestInfo(c).data;
	const collection = $app.dao().findCollectionByNameOrId("todos");
	const record = new Record(collection);
	const form = new RecordUpsertForm($app, record);
	form.loadData({
		field: data.todo,
		done: false,
	});
	form.submit();
});
```
But I think I want to return the HTML that contains the todo list which is this:

```
<ul class="todo-list">
  <% data.todos.forEach(function(todo){ %>
  <li class="<%= todo.done  ? 'completed' : '' %>">
    <div class="view">
      <input class="toggle" type="checkbox" <%= todo.done  ? 'checked' : '' %>>
      <label>
        <%= todo.field %>
      </label>
      <button class="destroy"></button>
    </div>
    <input class="edit" value="Create a TodoMVC template">
  </li>
  <% }); %>
</ul>
```

How can this be done?  I don't have access to EJS w/in the server side code.

**Comment by benallfree** [comment]
Instead of `routerAdd`, create a pocketpage like `api/newtodo.ejs` and handle it in there.

**Comment by bartonhammond** [comment]
Is there any documentation or example?  I don't understand what that ejs file would look like.

**Comment by benallfree** [comment]
https://pocketpages.dev/docs/routing#basic-example

**Comment by bartonhammond** [comment]
The file `newtodo.ejs` is located at `app/pages/api/newtodo.ejs`
```
console.log('newtodo');
<h1>Request Method: <%= ctx.method() %></h1>
<p>Request Path: <%= ctx.path() %></p>
```

The `index.ejs` has the form tag:
```
 <form hx-post="/api/newtodo" hx-trigger="submit" hx-target=".todo-list" hx-swap="afterbegin" hx-on::after-request="this.reset()" hx-swap="none">
      <input name="todo" class="new-todo" placeholder="What needs to be done?" autofocus>
    </form>
```

I get this error when submitting the form
```
htmx.org@2.0.2:1 Response Status Error Code 404 from /api/newtodo/
```

**Comment by bartonhammond** [comment]
I can not get the `api/newtodo` to work - it gets a 404 when submitting.

 If I put the file in `pages` directly it doesn't get a 404.  It gets a 405 - Method not allowed.
<img width="790" alt="Screenshot 2024-11-22 at 12 29 15 PM" src="https://github.com/user-attachments/assets/ab950763-e1c2-4cae-9534-8cdd5a36e249">

**Comment by benallfree** [comment]
I see there is a `/` at the end, I wonder if that has something to do with it. Can you browse directly to it and hit it?

**Comment by bartonhammond** [comment]
I've tried changing the various `/` - in the front, in the back, etc.

I can not access the page when it is w/in the `api`.  I can only access the page when it is in the root of `pages`.

When the `newtodo.ejs` is accessed as `http://127.0.0.1:8090/newtodo` and the page is this, it works
```
<h1>Hello</h1>
```

But if I update to this:
```
<h1>Hello</h1>
<h1>Request Method: <%= ctx.method() %></h1>
```
I get this:
```
PocketPages Error
TypeError: /newtodo.ejs:2
    1| <h1>Hello</h1>
 >> 2| <h1>Request Method: <%= ctx.method() %></h1>

Object has no member 'method'
	at anonymous (<eval>:12:36(32))
	at apply (native)
	at anonymous (node_modules/pocketpages/node_modules/pocketbase-ejs/lib/ejs.js:702:16(24))
	at node_modules/pocketpages/node_modules/pocketbase-ejs/lib/ejs.js:490:27(103)
	at renderFile (node_modules/pocketpages/src/main.ts:387:28(24))
	at node_modules/pocketpages/src/main.ts:419:31(387)
	at apply (native)
	at <eval>:3:35(8)
```

**Comment by benallfree** [comment]
I'll work on a fix.

**Comment by bartonhammond** [comment]
@benallfree Thanks!  Looking forward to it...

**Comment by bartonhammond** [comment]
If I change `api` to `foo` I can invoke but then still get the issue w/ ctx 
<img width="879" alt="Screenshot 2024-11-22 at 5 14 48 PM" src="https://github.com/user-attachments/assets/05532dfb-fa33-4039-9f21-b03c9419fd33">

**Comment by benallfree** [comment]
My mistake. `/api` is a reserved path and is forwarded straight to PocketBase. Use `xapi` or something like thiat.

v0.9.4 contains the updates you need, and I wrote an htmx tutorial and starter kit too.

https://pocketpages.dev/docs/htmx
https://github.com/benallfree/pocketpages/blob/main/starters/htmx/README.md

**Comment by benallfree** [comment]
`ctx.request().method`, right? 

https://pocketbase.io/jsvm/interfaces/http.Request.html#method
